FROM ubuntu:latest
WORKDIR /home/projects

RUN apt-get update && apt-get -y install \
    vim \
    iproute2 \
    iputils-ping \
    traceroute \
    tcpdump \
    dnsmasq \
    netcat-openbsd \
    python3 \
    curl \
    wget \
    gawk \
    dnsutils \
    procps

