version: '3.3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: cpp_for_procon
    volumes:
      - /Users/morimoto/Public/GitHub/procon/atcoder:/usr/src